---
# 🦫 Standard Overture Maps Foundation PR checks.
#
# Bundles the following checks:
#   - PR Title:      Validates PR titles against Overture's [TYPE] bracket format
#   - Check Issue:   Enforces that PRs have a linked GitHub issue
#
# Designed to run as a GitHub Ruleset required workflow.
#
name: OMF PR Checks

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:

  validate-pr-title:
    name: title
    uses: OvertureMaps/workflows/.github/workflows/validate-pr-title.yml@main

  check-linked-issue:
    name: issue
    uses: OvertureMaps/workflows/.github/workflows/check-issue.yml@main
    secrets: inherit
